POINT_CLOUD_FIELD_NAME_TO_DTYPE = {
    "X": "f0",
    "Y": "f1",
    "Z": "f2",
    "intensity": "f3",
    "return_number": "f4",
    "number_of_returns": "f5",
    "scan_direction_flag": "f6",
    "edge_of_flight_line": "f7",
    "classification": "f8",
    "synthetic": "f9",
    "key_point": "f10",
    "withheld": "f11",
    "scan_angle_rank": "f12",
    "user_data": "f13",
    "point_source_id": "f14",
    "red": "f15",
    "green": "f16",
    "blue": "f17",
}
